### ISSUE TITLE
Feature Request / Advice

### ISSUE THREAD

**Issue by bryangcooper** [MirzaBeig/Post-Processing-Scan#4]
Is there an easy way to set the shader to only pulse once?

**Comment by MirzaBeig** [comment]
This is now supported via the new [urp branch](https://github.com/MirzaBeig/Post-Processing-Scan/tree/urp) with the experimental single-pulse, transform-controlled scans.

~Thank you!

**Comment by MirzaBeig** [comment]
Closing.
